spring:
  application:
    name: project
  profiles:
    active: dev  # profile actif, peut être dev ou prod
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/project_elearningtn}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update       # pour dev, en prod mettre validate ou none
    show-sql: true           # logs SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false       # bonne pratique : éviter LazyInitializationException

server:
  port: 8080

app:
  cors:
    allowed-origins: "http://localhost:5173,http://127.0.0.1:5173,http://localhost:4173,http://127.0.0.1:4173"

jwt:
  secret: ${JWT_SECRET:change-me-please-change-me-please-change-me}
  expiration: 3600000
  cookie:
    name: access_token
    maxAge: 3600
    secure: false
    sameSite: Lax

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.example: DEBUG        # ton package, logs plus détaillés
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info    # pour actuator
  endpoint:
    health:
      show-details: always

swagger:
  enabled: true                # pour Swagger UI